workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.dohytai99.cccd"
      xcode: latest
      cocoapods: default
      flutter: stable
    scripts:
      - name: Update Flutter
        script: |
          flutter upgrade
      - name: Create Flutter project
        script: |
          cd $CM_BUILD_DIR
          rm -rf *
          flutter create --org com.dohytai99 cccd
          cd cccd
          # Tạo pubspec.yaml với các dependency cần thiết
          cat > pubspec.yaml << 'EOL'
          name: cccd
          description: CCCD Scanner App
          version: 1.0.0+1

          environment:
            sdk: ">=2.19.0 <4.0.0"

          dependencies:
            flutter:
              sdk: flutter
            flutter_nfc_kit: ^3.4.2
            cupertino_icons: ^1.0.2

          dev_dependencies:
            flutter_test:
              sdk: flutter
            flutter_lints: ^2.0.0

          flutter:
            uses-material-design: true
          EOL
      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR/cccd
          flutter clean
          flutter pub get
      - name: Configure Podfile
        script: |
          cd $CM_BUILD_DIR/cccd/ios
          # Tạo Podfile mới với cấu hình phiên bản iOS
          cat > Podfile << 'EOL'
          platform :ios, '13.0'

          # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }

          def flutter_root
            generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
            unless File.exist?(generated_xcode_build_settings_path)
              raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
            end

            File.foreach(generated_xcode_build_settings_path) do |line|
              matches = line.match(/FLUTTER_ROOT\=(.*)/)
              return matches[1].strip if matches
            end
            raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
          end

          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

          flutter_ios_podfile_setup

          target 'Runner' do
            use_frameworks!
            use_modular_headers!

            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
              target.build_configurations.each do |config|
                config.build_settings['ENABLE_BITCODE'] = 'NO'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
              end
            end
          end
          EOL
      - name: Update project settings
        script: |
          cd $CM_BUILD_DIR/cccd/ios
          # Cập nhật minimum deployment target trong project.pbxproj
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' Runner.xcodeproj/project.pbxproj
      - name: Install pods
        script: |
          cd $CM_BUILD_DIR/cccd/ios && pod install
      - name: Update bundle ID and build settings
        script: |
          cd $CM_BUILD_DIR/cccd/ios
          # Cập nhật Bundle ID trong Info.plist
          PLIST_PATH="Runner/Info.plist"
          PLIST_BUDDY="/usr/libexec/PlistBuddy"
          $PLIST_BUDDY -c "Set :CFBundleIdentifier $BUNDLE_ID" "$PLIST_PATH"
          
          # Thêm entitlements cho TrollStore
          ENTITLEMENTS_PATH="Runner/Runner.entitlements"
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>get-task-allow</key>
              <true/>
              <key>com.apple.security.application-groups</key>
              <array/>
              <key>application-identifier</key>
              <string>com.dohytai99.cccd</string>
          </dict>
          </plist>' > "$ENTITLEMENTS_PATH"
      - name: Build and prepare IPA for TrollStore
        script: |
          cd $CM_BUILD_DIR/cccd
          
          # Build IPA
          flutter build ipa --no-codesign
          
          # Extract the IPA
          cd build/ios/ipa
          mv *.ipa original.ipa
          unzip original.ipa -d extracted
          
          # Modify Info.plist
          cd extracted/Payload/*.app
          PLIST_BUDDY="/usr/libexec/PlistBuddy"
          $PLIST_BUDDY -c "Delete :CFBundleIdentifier" Info.plist || true
          $PLIST_BUDDY -c "Add :CFBundleIdentifier string com.dohytai99.cccd" Info.plist
          $PLIST_BUDDY -c "Delete :CFBundleExecutable" Info.plist || true
          $PLIST_BUDDY -c "Add :CFBundleExecutable string Runner" Info.plist
          $PLIST_BUDDY -c "Delete :CFBundleName" Info.plist || true
          $PLIST_BUDDY -c "Add :CFBundleName string CCCD Scanner" Info.plist
          
          # Create new IPA
          cd ../..
          zip -r ../trollstore.ipa Payload
          cd ..
          mv trollstore.ipa $CM_BUILD_DIR/build/ios/ipa/
          
          # Clean up
          rm -rf extracted
          rm original.ipa
          
          # Verify IPA structure
          unzip -l trollstore.ipa | grep Info.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - dohytai99@gmail.com 