workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.dohytai99.cccd
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.dohytai99.cccd"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          cd ios && pod install
      - name: Update bundle ID and entitlements
        script: |
          cd ios
          PLIST_PATH="Runner/Info.plist"
          PLIST_BUDDY="/usr/libexec/PlistBuddy"
          $PLIST_BUDDY -c "Set :CFBundleIdentifier $BUNDLE_ID" "$PLIST_PATH"
          
          ENTITLEMENTS_PATH="Runner/Runner.entitlements"
          /usr/libexec/PlistBuddy -c "Add :get-task-allow bool true" "$ENTITLEMENTS_PATH" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :com.apple.security.application-groups array" "$ENTITLEMENTS_PATH" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :com.apple.developer.team-identifier string XXXXXXXXXX" "$ENTITLEMENTS_PATH" 2>/dev/null || true
      - name: Flutter build ipa
        script: |
          flutter build ipa --debug
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - dohytai99@gmail.com 